nmHoistingLimits: dependencies
nodeLinker: node-modules

packageExtensions:
  "styled-components@*":
    dependencies:
      "react-is": "*"
  "ts-loader@*":
    dependencies:
      "webpack": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs