FROM node:16.13.2-buster

ARG TZ=Europe/London

# Set the server timezone
RUN mv /etc/localtime /etc/localtime.bak
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /src

COPY ./package.json .
COPY ./yarn.lock .
COPY ./.yarn .
COPY ./.husky .
COPY ./tsconfig.json .
COPY ./tsconfig.settings.json .
COPY ./app ./app
COPY ./docker.env ./app
COPY ./api ./api

RUN yarn install
# Loading external environment variables work around (NextJS) need them at build-time
RUN mv /src/app/docker.env /src/app/.env.production
RUN cd ./app && NODE_ENV=production yarn build

CMD cd ./app && NODE_ENV=production yarn start

EXPOSE 3000