FROM node:16.13.2-buster

ARG TZ=Europe/London

# Set the server timezone
RUN mv /etc/localtime /etc/localtime.bak
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /src

COPY ./package.json .
COPY ./yarn.lock .
COPY ./.yarn .
COPY ./.husky .
COPY ./tsconfig.json .
COPY ./tsconfig.settings.json .
COPY ./api ./api

RUN yarn install
RUN cd ./api && yarn build api-gateway

CMD cd ./api && node dist/packages/api-gateway/main.js

EXPOSE 4000